<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>0.7.0</Version>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\discord_icon.png" />
    <AvaloniaResource Include="Assets\app_icon.png" />
    <EmbeddedResource Include="Assets\TooltipIcons\*.png" />
    <AvaloniaResource Include="Assets\TooltipIcons\ico_gold.png" />
    <AvaloniaResource Include="Assets\TooltipIcons\ico_weight_normal.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\langs\*.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParaTool.Core\ParaTool.Core.csproj" />
  </ItemGroup>

</Project>
